// model/norte.dart
class ZonaNorte {
  static const List<String> bairros = [
    'Acarape',
    'Aeroporto',
    'Água Mineral',
    'Alto Alegre',
    'Aroeiras',
    'Bom Jesus',
    'Buenos Aires',
    'Chapadinha',
    'Cidade Industrial',
    'Embrapa',
    'Itaperu',
    'Jacinta Andrade',
    'Mafrense',
    'Matadouro',
    'Memorare',
    'Monte Verde',
    'Mocambinho',
    'Morro da Esperança',
    'Nova Brasília',
    'Olarias',
    'Parque Alvorada',
    'Parque Brasil',
    'Poti Velho',
    'Primavera',
    'Real Copagre',
    'Santa Maria da Codipe',
    'Santa Rosa',
    'Santa Sofia',
    'São Joaquim',
    'Vila Operária',
    'Vila São Francisco',
  ];
}
