class ZonaSul{
  static const List<String> bairros = [
    'Angelim',
    'Irmã Dulce',
    'Lourival Parente',
    'Bela Vista I',
    'Bela Vista II',
    'Morada Nova',
    'Areias',
    'Distrito Industrial',
    'Km Sete',
    'Saci',
    'Promorar',
    'Parque Piauí',
    'Planalto Bela Vista',
    'Parque Sul',
    'Eduardo Costa',
    'Residencial Torquato Neto IV',
    'Pio XII',
    'Catarina',
    'Monte Castelo',
    'Macaúba',
    'Cristo Rei',
    'Pedra Muida',
    'Brasilar',
    'Santo Antonio',
    'Vermelha',
    'Esplanada',
    'Tabuleta ',
    'Cidade Nova',
    'Mário Covas',
    'Santa Cruz',
    'Jacinta Andrade',

  ];
}