// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEIOvC5GR2HgxpxOB3O5EyVT0O4f2O4wg',
    appId: '1:526811594491:web:e4d0b466d288f8ee75fa5e',
    messagingSenderId: '526811594491',
    projectId: 'quanto-custa-the-c5edd',
    authDomain: 'quanto-custa-the-c5edd.firebaseapp.com',
    storageBucket: 'quanto-custa-the-c5edd.firebasestorage.app',
    measurementId: 'G-FLESF60PNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMC3YbFLll7M_ZIEwIGH6zZQ1eHznN-2Y',
    appId: '1:526811594491:android:c77ddee8e7cbafe175fa5e',
    messagingSenderId: '526811594491',
    projectId: 'quanto-custa-the-c5edd',
    storageBucket: 'quanto-custa-the-c5edd.firebasestorage.app',
  );
}
